package com.thulasi.easyway.type;

public enum SalesOrderStatus {

	ORDER_PENDING, ORDER_CONFIRMED, ORDER_CANCELLED, ORDER_COMPLETED, PAYMENT_PENDING, PAYMENT_COMPLETED,
	DELIVERY_PENDING, DELIVERY_SHIPPED, DELIVERY_COMPLETED, DELIVERY_CANCELLED, DELIVERY_RETURNED

}
